### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by hyyven** [ImTheSquid/SplitLargeFiles#29]
![image](https://github.com/ImTheSquid/SplitLargeFiles/assets/130588672/4e5d3e22-3a20-4476-ab93-6fd671e8e5a5)

**Comment by Shadowkj1** [comment]
![Screenshot 2023-12-06 202951](https://github.com/ImTheSquid/SplitLargeFiles/assets/41036282/965f312b-5a49-45d3-9ca0-9a6566078999)
I am also experiencing the same issue. when just putting only the js into the plugins folder

**Comment by ghost** [comment]
@Shadowkj1 "when just putting only the js into the plugins folder" what do you mean by that? Do you mean at other circumstances the error doesn't appear? It's just that I have the same issue with the plugin

**Comment by Shadowkj1** [comment]
@Valdemarcheck The only way I have tested is by putting the Js file into the plugins folder, which results in the error. I have only experienced the error, no success in using the plugin. Apologies for the poor wording lol

**Comment by Chaxiraxi** [comment]
+1, the same problem
```js
TypeError: Cannot convert undefined or null to object
at Function.values (<anonymous>)
at plugin (betterdiscord://plugins/SplitLargeFiles.plugin.js:98:37)
at eval (betterdiscord://plugins/SplitLargeFiles.plugin.js:637:13)
at eval (betterdiscord://plugins/SplitLargeFiles.plugin.js:638:3)
at A.requireAddon (betterdiscord/renderer.js:5:33832)
at A.loadAddon (betterdiscord/renderer.js:5:6386)
at A.loadAddon (betterdiscord/renderer.js:5:31500)
at A.loadAllAddons (betterdiscord/renderer.js:5:8878)
at A.initialize (betterdiscord/renderer.js:5:3258)
at A.initialize (betterdiscord/renderer.js:5:30699)
at Object.startup (betterdiscord/renderer.js:5:369099)
```

**Comment by Crisstiian2303** [comment]
i got the same issue, is there any fix?

**Comment by ghost** [comment]
also got the issue....

**Comment by Dorko316** [comment]
Same here
